# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["day*"]

[workspace.package]
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.66"
thiserror = "1.0.37"
